sudo: false
language: ruby
cache: bundler
before_script: bundle update
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rspec
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/ar_5.0_pt_4.0.gemfile
  - gemfiles/ar_5.0_pt_5.0.gemfile
  - gemfiles/ar_5.1_pt_4.0.gemfile
  - gemfiles/ar_5.1_pt_5.0.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
