# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: ar_5.2_pt_10.3
            ruby: 2.5

          - gemfile: ar_5.2_pt_10.3
            ruby: 2.6

          - gemfile: ar_6.0_pt_10.3
            ruby: 2.6

          - gemfile: ar_6.0_pt_10.3
            ruby: 2.7

          - gemfile: ar_6.1_pt_12.3
            ruby: 2.6

          - gemfile: ar_6.1_pt_12.3
            ruby: 2.7

          - gemfile: ar_6.1_pt_12.3
            ruby: 3.0

    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Bundle install
        run: |
          bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec
